# Generated by Django 4.2.2 on 2023-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0046_alter_customgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(default=1, null=True, verbose_name='Nombre de membres'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Cette adresse email est déjà utilisée.'}, max_length=254, unique=True, verbose_name='Adresse e-mail'),
        ),
    ]
